name: Multi-Stage Docker Builds

on:
  push:
    branches: [ "mai000n" ]
  pull_request:
    branches: [ "maiooon" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Logging into the Docker Hub
      uses: docker/login-action@v1
      with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}
          
    - name: Pushing the Image to Docker Hub
      run: |
            docker push frehman/pipe1:$IMAGE_VERSION
            
    - name: echo kar raha hu
      run: |
             echo "uzair"
            
